#ifndef CONSTANTS_SHELLCONSTANTS_H
#define CONSTANTS_SHELLCONSTANTS_H

#define COMMAND_MAX_LEN     512
#define NUM_PREVIOUS_INPUTS 32

#define RETURN_SUCCESS 0
#define RETURN_ERROR   1

#endif